### ISSUE TITLE
GUI doesn't open in Wayland

### ISSUE THREAD

**Issue by woshiahmedc** [keyiflerolsun/BTKSorgu#1]
When I try to open the app from console using _" flatpak run org.KekikAkademi.BTKSorgu "_ , it returns with that error 

"
Tk_Init error: no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/app/bin/BTKSorguGUI", line 8, in <module>
    sys.exit(basla())
  File "/app/lib/python3.10/site-packages/BTKSorgu/arayuz.py", line 6, in basla
    ui = KekikGUI()
  File "/app/lib/python3.10/site-packages/BTKSorgu/KekikGUI.py", line 14, in __init__
    super().__init__()
  File "/app/lib/python3.10/site-packages/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
"

**Comment by keyiflerolsun** [comment]
what is your display server?

**Comment by woshiahmedc** [comment]
My display server is mutter, I'm in GNOME v44

**Comment by keyiflerolsun** [comment]
> My display server is mutter, I'm in GNOME v44

probably tk/tcl is not working in wayland..

**Comment by keyiflerolsun** [comment]
Does `BTKSorguGUI` open when you install `BTKSorgu` with pip?

**Comment by woshiahmedc** [comment]
When I try to install using pip it says succesfully installed

" Successfully installed BTKSorgu-1.3.6 Pillow-9.5.0 certifi-2023.5.7 charset-normalizer-3.1.0 cssselect-1.2.0 idna-3.4 install-freedesktop-0.1.2 jmespath-1.0.1 lxml-4.9.2 markdown-it-py-2.2.0 mdurl-0.1.2 parsel-1.8.1 pygments-2.15.1 pytesseract-0.3.10 regex-2023.5.5 requests-2.31.0 rich-13.3.5 sv-ttk-2.4.5 urllib3-2.0.2 w3lib-2.1.1 "

But when I try to open the app using " BTKSorguGUI ", console returns bash: " BTKSorguGUI: command not found "
